import React from 'react'
import Head from 'next/head'
import Header from '../../components/Header';
import Footer from '../../components/Footer';
import Link from 'next/link';
import { useRouter } from 'next/router'
import { getUrl } from '../../services/getUrl';

export async function getStaticProps(context) {

  let categories;
  categories = await fetch(`${getUrl()}/categories?_locale=pl-PL&_sort=updatedAt:DESC`);
  const categoriesData = await categories.json();

  let header;
  header = await fetch(`${getUrl()}/header?_locale=pl-PL`);
  const headerData = await header.json();

  let footer;
  footer = await fetch(`${getUrl()}/footer?_locale=pl-PL`);
  const footerData = await footer.json();

  return {
    props: {
      categories: categoriesData,
      header: headerData,
      footer: footerData,
    },
    revalidate: 2
  }
}

function Index({ categories, header, footer }) {
  const router = useRouter()

    return (
        <div>
    <Head>
        <title>CATEGORIES</title>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed:wght@300;400;700&display=swap" rel="stylesheet" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <Header header={header} />
        <div className="categories-content">
            <div className="wrapper">
              {
                categories.map(category => 
                  <Link key={category._id} href={`/categories/${category.slug}`} passHref>
                    <a>
                  <div className="item" style={{ backgroundImage: `url('${category.image.url}')`}}>
                    <h1>{category.title}</h1>
                  </div>
                  </a>
                  </Link>
                  )
              }
                   {/* <Link href={`/categories`} passHref>
                    <a>
                  <div className="item" style={{ backgroundImage: `url('https://unsplash.it/700/700')`}}>
                    <h1>TEST TEST</h1>
                  </div>
                  </a>
                  </Link>
                  <Link href={`/categories`} passHref>
                    <a>
                  <div className="item" style={{ backgroundImage: `url('https://unsplash.it/700/700')`}}>
                    <h1>TEST TEST</h1>
                  </div>
                  </a>
                  </Link> */}
            </div>
        </div>
      </main>
      <Footer footer={footer} />
        </div>
    )
}

export default Index
