import React from 'react'
import Head from 'next/head'
import Header from '../../components/Header';
import Footer from '../../components/Footer';
import Link from 'next/link';
import { useRouter } from 'next/router'

export async function getStaticProps(context) {

  const { locale, defaultLocale } = context;

  let categories;
  if (locale === undefined) {
    categories = await fetch(`http://localhost:1337/categories`);
  } else {
    categories = await fetch(`http://localhost:1337/categories?_locale=${locale}`);
  }
  const categoriesData = await categories.json();

  let header;
  if (locale === undefined) {
    header = await fetch(`http://localhost:1337/header`);
  } else {
    header = await fetch(`http://localhost:1337/header?_locale=${locale}`);
  }
  const headerData = await header.json();

  let footer;
  if (locale === undefined) {
    footer = await fetch(`http://localhost:1337/footer`);
  } else {
    footer = await fetch(`http://localhost:1337/footer?_locale=${locale}`);
  }
  const footerData = await footer.json();

  return {
    props: {
      categories: categoriesData,
      header: headerData,
      footer: footerData,
      locale
    }
  }
}

function Index({ categories, header, footer, locale }) {
  const router = useRouter()

    return (
        <div>
    <Head>
        <title>CATEGORIES</title>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link href="https://fonts.googleapis.com/css2?family=Rajdhani:wght@300;400;500;600;700&display=swap" rel="stylesheet" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <Header header={header} locale={locale} asPath={router.asPath} type="categories"/>
        <div className="categories-content">
            <div className="wrapper">
              {
                categories.map(category => 
                  <Link key={category._id} href={`/categories/${category.slug}`} locale={category.locale} passHref>
                    <a>
                  <div className="item" style={{ backgroundImage: `url('${category.image.url}')`}}>
                    <h1>{category.title}</h1>
                  </div>
                  </a>
                  </Link>
                  )
              }
                   {/* <Link href={`/categories`} passHref>
                    <a>
                  <div className="item" style={{ backgroundImage: `url('https://unsplash.it/700/700')`}}>
                    <h1>TEST TEST</h1>
                  </div>
                  </a>
                  </Link>
                  <Link href={`/categories`} passHref>
                    <a>
                  <div className="item" style={{ backgroundImage: `url('https://unsplash.it/700/700')`}}>
                    <h1>TEST TEST</h1>
                  </div>
                  </a>
                  </Link> */}
            </div>
        </div>
      </main>
      <Footer footer={footer} locale={locale} />
        </div>
    )
}

export default Index
