import Head from 'next/head'
import Link from 'next/link';
import { Swiper, SwiperSlide } from 'swiper/react';
import SwiperCore, {Navigation, Pagination, Autoplay} from 'swiper';
import 'swiper/css';
import Header from '../components/Header';
import Footer from '../components/Footer';
import { useRouter } from 'next/router'
import { getUrl } from '../services/getUrl';

SwiperCore.use([Navigation, Pagination, Autoplay]);

export async function getStaticProps(context) {

  const { locale, defaultLocale } = context;

  let page;
  if (locale === undefined) {
    page = await fetch(`${getUrl()}/pagrindinis`);
  } else {
    page = await fetch(`${getUrl()}/pagrindinis?_locale=${locale}`);
  }
  const pageData = await page.json();

  let header;
  if (locale === undefined) {
    header = await fetch(`${getUrl()}/header`);
  } else {
    header = await fetch(`${getUrl()}/header?_locale=${locale}`);
  }
  const headerData = await header.json();

  let footer;
  if (locale === undefined) {
    footer = await fetch(`${getUrl()}/footer`);
  } else {
    footer = await fetch(`${getUrl()}/footer?_locale=${locale}`);
  }
  const footerData = await footer.json();

  return {
    props: {
      page: pageData,
      header: headerData,
      footer: footerData,
      locale
    }
  }
}

export default function Home({ page, header, footer, locale}) {

  const router = useRouter()

  return (
    <div>
      <Head>
        <title>SKODAS.LT</title>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link href="https://fonts.googleapis.com/css2?family=Rajdhani:wght@300;400;500;600;700&display=swap" rel="stylesheet" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header header={header} locale={locale} asPath={router.asPath} type={`home`}/>
        <Swiper
            // spaceBetween={50}
            // modules={[Navigation, Pagination]}
            slidesPerView={1}
            onSwiper={(swiper) => console.log(swiper)}
            navigation
            pagination={{ clickable: true }}
            autoplay
          >
            {
              page.Slideshow.images.map(image =>
                <SwiperSlide key={image._id}>
                  <div className="slide-item" style={{ backgroundImage: `url('${image.url}')`}}>
                    
                  </div>
                </SwiperSlide>
                )
            }
          </Swiper>
          <div className="about-content">
            <div className="wrapper">
              <div className="image">
                <img src="https://res.cloudinary.com/skodas-lt/image/upload/v1632901194/56767-11965575_asp7jp.jpg" />
              </div>
              <div className="text">
                <h2>{page.title}</h2>
                <div className="paragraph" dangerouslySetInnerHTML={{ __html: page.content }} />
              </div>
            </div>
          </div>
      </main>
        <Footer footer={footer} locale={locale} />
    </div>
  )
}
