import Head from 'next/head'
import SwiperCore, {Navigation, Pagination, Autoplay} from 'swiper';
import 'swiper/css';
import Header from '../../components/Header';
import Footer from '../../components/Footer';
import { useRouter } from 'next/router'
import { getUrl } from '../../services/getUrl';

SwiperCore.use([Navigation, Pagination, Autoplay]);

export async function getStaticProps(context) {

  const { locale, defaultLocale } = context;

  let page;
  if (locale === undefined) {
    page = await fetch(`${getUrl()}/kontaktai`);
  } else {
    page = await fetch(`${getUrl()}/kontaktai?_locale=${locale}`);
  }
  const pageData = await page.json();

  let header;
  if (locale === undefined) {
    header = await fetch(`${getUrl()}/header`);
  } else {
    header = await fetch(`${getUrl()}/header?_locale=${locale}`);
  }
  const headerData = await header.json();

  let footer;
  if (locale === undefined) {
    footer = await fetch(`${getUrl()}/footer`);
  } else {
    footer = await fetch(`${getUrl()}/footer?_locale=${locale}`);
  }
  const footerData = await footer.json();

  return {
    props: {
      page: pageData,
      header: headerData,
      footer: footerData,
      locale
    }
  }
}

export default function Index({ page, header, footer, locale}) {

  const router = useRouter()
  console.log(page);

  return (
    <div>
      <Head>
        <title>SKODAS.LT</title>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link href="https://fonts.googleapis.com/css2?family=Rajdhani:wght@300;400;500;600;700&display=swap" rel="stylesheet" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header header={header} locale={locale} asPath={router.asPath} type="services"/>
          <div className="services-content">
            <h1>{page.title}</h1>
            <div className="wrapper">
              <div className="paragraph" dangerouslySetInnerHTML={{ __html: page.content }} />
            </div>
          </div>
      </main>
        <Footer footer={footer} locale={locale} />
    </div>
  )
}
